# Generated by Django 4.1.1 on 2022-09-08 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormaZone_HTML', '0004_alter_widget_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widget',
            name='Option',
            field=models.CharField(max_length=100, verbose_name='nom_departement'),
        ),
        migrations.AlterField(
            model_name='widget',
            name='Prix',
            field=models.CharField(max_length=100, verbose_name='frais_ttc_tot_max'),
        ),
        migrations.AlterField(
            model_name='widget',
            name='Temps',
            field=models.CharField(max_length=1000, verbose_name='nombre_heures_total_max'),
        ),
    ]
