# Generated by Django 4.1.1 on 2022-09-06 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormaZone_HTML', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='widget',
            name='Option',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='widget',
            name='Prix',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='widget',
            name='Temps',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
