# Generated by Django 4.1.1 on 2022-09-08 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormaZone_HTML', '0002_widget_option_widget_prix_widget_temps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widget',
            name='Title',
            field=models.CharField(max_length=1000, verbose_name='intitule_formation'),
        ),
    ]
