# Generated by Django 4.1.1 on 2022-09-08 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormaZone_HTML', '0003_alter_widget_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widget',
            name='Title',
            field=models.CharField(max_length=10000, verbose_name='intitule_formation'),
        ),
    ]
